apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster1
  region: us-east-1

nodeGroups:
  - name: linux-nodes
    instanceType: t3.micro
    desiredCapacity: 2
    spot: true